server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./hype_db;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  s3:
    accessKey: IPw9LKx9C7f8y1VN32kP
    secretKey: VMZkSDkfxuGgVnetHIuFHAAAjZMVjwXoXI3UpuRA
    bucket: hypeimagebucket
    testBucket: hypetestbucket
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    com.ll.sb20231114: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE